
import React, { createContext, useContext, useState, useEffect } from 'react';
import { toast } from 'sonner';
import { 
  User, 
  AuthContextType, 
  SignUpData,
  LoginFormValues
} from './types';
import { 
  getUserFromStorage, 
  saveUserToStorage, 
  removeUserFromStorage,
  findUserByCredentials,
  createUserWithoutPassword,
  checkIfEmailExists,
  generatePassword,
  handleEmployeeAccounts
} from './authUtils';

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export const AuthProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [user, setUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(true);

  // Check for existing session on mount
  useEffect(() => {
    const checkAuth = () => {
      const storedUser = getUserFromStorage();
      if (storedUser) {
        setUser(storedUser);
      }
      setIsLoading(false);
    };

    checkAuth();
  }, []);

  const login = async (formData: LoginFormValues) => {
    const { email, password } = formData;
    setIsLoading(true);
    
    try {
      // Simulate API call delay
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      const foundUser = findUserByCredentials(email, password);
      
      if (foundUser) {
        const userWithoutPassword = createUserWithoutPassword(foundUser);
        
        setUser(userWithoutPassword);
        saveUserToStorage(userWithoutPassword);
        toast.success('Welcome back!');
      } else {
        throw new Error('Invalid email or password');
      }
    } catch (error) {
      if (error instanceof Error) {
        toast.error(error.message);
      } else {
        toast.error('Failed to login');
      }
      throw error;
    } finally {
      setIsLoading(false);
    }
  };

  const signUp = async (userData: SignUpData) => {
    setIsLoading(true);
    
    try {
      // Simulate API call delay
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      // Check if email already exists
      if (checkIfEmailExists(userData.email)) {
        throw new Error('Email already in use');
      }

      // Generate a random password (in a real app, this would be done server-side)
      const generatedPassword = generatePassword();
      
      // In a real app, you would send an email with the generated password here
      console.log(`Generated password for ${userData.email}: ${generatedPassword}`);
      
      // Create new user (in a real app, this would be handled by the backend)
      const newUserId = `3`; // This would be generated by the backend
      const newUser: User = {
        id: newUserId,
        email: userData.email,
        name: userData.name,
        role: 'manager', // Set the main account as a manager role
        agency: userData.agency,
        country: userData.country,
        phone: userData.phone,
        balance: 0
      };

      // Handle employee accounts if they exist
      handleEmployeeAccounts(userData.employees);

      // If no employees, show a different success message
      if (!userData.employees || userData.employees.length === 0) {
        // Notify user about password email (only for the main account)
        toast.success('Account created! Check your email for your password.');
      }

      // In a real app, we would save this to the backend
      setUser(newUser);
      saveUserToStorage(newUser);
    } catch (error) {
      if (error instanceof Error) {
        toast.error(error.message);
      } else {
        toast.error('Failed to create account');
      }
      throw error;
    } finally {
      setIsLoading(false);
    }
  };

  const logout = () => {
    setUser(null);
    removeUserFromStorage();
    toast.info('You have been logged out');
  };

  return (
    <AuthContext.Provider
      value={{
        user,
        isAuthenticated: !!user,
        isLoading,
        login,
        signUp,
        logout
      }}
    >
      {children}
    </AuthContext.Provider>
  );
};

export const useAuthContext = () => {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error('useAuthContext must be used within an AuthProvider');
  }
  return context;
};
